---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
First, we make sure that all code chunks are visible:

library(knitr)
opts_chunk$set(echo=TRUE)

## Loading and preprocessing the data
#Load the data (i.e. read.csv())
if(!file.exists('activity.csv')){
    unzip('activity.zip')
}
activityData <- read.csv('activity.csv', header = T, sep = ",")
#Process/transform the data (if necessary) into a format suitable for your analysis
activityData$date <- as.Date(activityData$date)

str(activityData)


## What is mean total number of steps taken per day?

#Calculate the total number of steps taken per day
The total steps per day are summed up using the tapply function.

activityDataSteps <- tapply(activityData$steps, activityData$date, sum, na.rm=T)
Histogram of the total number of steps taken each day
library(reshape2)
activityDataMelt <- melt(activityDataSteps)
names(activityDataMelt) <- c("Date", "SumofSteps")
head(activityDataMelt)

hist(activityDataMelt$SumofSteps, main = "Histogram of Total Number of Steps per Day", 
    xlab = "Total Number of Steps per Day", ylab = "Frequency", col = "blue", 
    breaks = 30)
Calculate and report the mean and median of the total number of steps taken per day
The mean

step_mean <- mean(activityDataMelt$SumofSteps, na.rm = T)
step_mean
The median

step_median <- median(activityDataMelt$SumofSteps, na.rm = T)
step_median

## What is the average daily activity pattern?

#A time series plot (i.e. ???????????????? = "????") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
activityDataAvg <- tapply(activityData$steps, activityData$interval, mean, na.rm = T)
activityDataMeltAvg <- melt(activityDataAvg)
names(activityDataMeltAvg) <- c("interval", "avg")
nrow(activityDataMeltAvg)
plot(avg ~ interval, data = activityDataMeltAvg, type = "l", main = "Average daily activity pattern")
The 5-minute interval, on average across all the days in the dataset, that contains the maximum number of steps
activityDataMeltAvg[activityDataMeltAvg$avg == max(activityDataMeltAvg$avg), ]

## Imputing missing values
The total number of missing values in the dataset (i.e. the total number of rows wih NAs)
length(which(is.na(activityData$steps)))
Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
mean(activityData$steps, na.rm = T)
Create a new dataset that is equal to the original dataset but with the missing data filled in.
activityDataImpute <- activityData
activityDataImpute$steps[is.na(activityDataImpute$steps)] <- mean(activityDataImpute$steps, na.rm = T)
length(which(is.na(activityDataImpute)))
Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?
``{r} activityDataImputeSteps <- tapply(activityDataImpute$steps, activityDataImpute$date, sum)

library(reshape2) activityDataMeltImpute <- melt(activityDataImputeSteps) names(activityDataMeltImpute) <- c("Date", "SumofSteps") head(activityDataMeltImpute)

hist(activityDataMeltImpute$SumofSteps, main = "Histogram of Total Number of Steps per Day on Impute Value", xlab = "Total Number of Steps per Day", ylab = "Frequency", col = "blue", breaks = 30)

mean(activityDataMeltImpute$SumofSteps, na.rm = T)

median(activityDataMeltImpute$SumofSteps, na.rm = T)


## Are there differences in activity patterns between weekdays and weekends?
1. Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

```{r}
activityDataImpute$weekdays <- weekdays(activityDataImpute$date)
activityDataImpute$weeks[(activityDataImpute$weekdays == "Saturday" | activityDataImpute$weekdays == "Sunday")] <-"weekend"

activityDataImpute$weeks[!(activityDataImpute$weekdays == "Saturday" | activityDataImpute$weekdays == "Sunday")] <-"weekdays"
library(plyr)
week_comp <- ddply(activityDataImpute, c("interval", "weeks"), function(x) apply(x[1], 
    2, mean))
head(week_comp)
Make a panel plot containing a time series plot (i.e. ???????????????? = "????") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.
library(lattice)
xyplot(steps ~ interval | weeks, data = week_comp, type = "l", xlab = "Interval", 
    ylab = "Number of steps", layout = c(1, 2))
